version: '3.7'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run watch"
    ports:
      - '8080:8080'
